Makefile

before running lint, test and build which takes time.

chore: checks if the target version for release already exists 

---

src/hypertrace/agent/instrumentation/grpc/__init__.py

```
exception.escaped: False
exception.type: IndexError
exception.message: tuple index out of range
message: exception
exception.stacktrace: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/hypertrace/agent/instrumentation/grpc/__init__.py", line 209, in telemetry_interceptor context.get_trailing_metadata()[0], response, span) IndexError: tuple index out of range
```

chore(grpc): avoids exceptions when emptry trailing metadata in server.

---

.github/workflows/merge.yml
.github/workflows/release.yml
dev-requirements.txt
src/hypertrace/agent/config/environment_test.py
tests/aiohttp/requirements.txt

Pipeline failure on code from main - it looks like this has something to do with python 3.8.10 on ubuntu in the postgres test, I tested locally with 3.8.10 and couldn't reproduce(the test passed) - the last successful run on main used 3.8.5. 
This updates some of the pipeline steps to allow us to specify a patch specific python version as well as moves some of the `sudo` installed dependencies into their associated requirements.txt file.
I had to update it to use the github action for python instead of apt-get install because we can't specify a patch specific version
The goal here is to unblock other changes, not necessarily fix the root issue.

pipeline adjustments to unblock changes

---

src/hypertrace/agent/instrumentation/flask/__init__.py
tests/flask/test_flask_11.py
tests/flask/tox.ini

If a user attempts to return a response with a file, reading body will error because of this werkzeug logic:
https://github.com/pallets/werkzeug/blob/f7b53ee8a81f015c6c85659959004328237a3c8c/src/werkzeug/wrappers/response.py#L348-L371
(specifically the `direct_passthrough` exception at the above link)
Rather than attempting to read it and log an error just skip if direct_passthrough is set.
Recreated in local flask app: 
```
@app.route('/')
def hello_world():
return send_file("./app.py")
```
Which will produce this exception:
```
ERROR:hypertrace.agent.instrumentation.flask:An error occurred in flask after_request handler: exception=Attempted implicit sequence conversion but the response object is in direct passthrough mode., stacktrace=Traceback (most recent call last):
File …
```

Add handling for direct_passthrough resp body with file

---

src/hypertrace/agent/instrumentation/__init__.py
tests/flask/test_flask_11.py

Attempting to decode a unicode string uses a default mode of `strict`, which can raise a
`UnicodeDecodeError` & prevent body capture.  
Recreated locally in sample app, added endpoint + test case.

UnicodeDecodeError in body parsing

---

src/hypertrace/agent/config/__init__.py
src/hypertrace/agent/config/__init___test.py
src/hypertrace/agent/config/file_test.py

The goal here is to remove the internal config dictionary validation to enable filter libraries to add additional key values that hypertrace doesn't need to be aware of(or log an error because of)
I attempted to migrate this to entirely use protobuf models; however, that would break existing users programatic configured agent options(such as through `agent.edit_config`)
Python specific attributes are stored in a new attribute `custom_config`, and removed before converting config dict to proto.

Skip config dict validation

---

src/hypertrace/agent/__init__.py

This file is loaded as part of agent initialization so we shouldn't depend on external types that may not exist in a given python env.

Remove flask import if we don't know flask exists

---

.pylintrc
src/hypertrace/agent/filter/__init__.py
src/hypertrace/agent/filter/registry.py
src/hypertrace/agent/filter/test_registry.py
src/hypertrace/agent/instrumentation/__init__.py
src/hypertrace/agent/instrumentation/aiohttp/__init__.py
src/hypertrace/agent/instrumentation/flask/__init__.py
src/hypertrace/agent/instrumentation/grpc/__init__.py
src/hypertrace/agent/instrumentation/requests/__init__.py

The goal here is to handle some low hanging fruit to improve performance: 
1.) Less `logger.debug("some message %s", str(a_span))`
Even though the log messages dont have the stringified objects interpolated when not in debug logging the `str` cast call still occurs.
(This does get costly when doing it per req for every header + body)
2.) headers tuple → dict
We were adding some overhead in multiple instrumentations because we were converting a header dict to a list of tuples. Using a dict instead gives us a few benefits: 
- content type lookup can be simple key lookup, no need to iterate over all headers
- Saves us a conversions from dict to tuple
left = current released version, right = this PR
The profiler data below has been filtered to just show hypertrace calls. 
The important detail …

Perf Improvements

---

src/hypertrace/agent/instrumentation/grpc/__init__.py
tests/grpc/test_grpc_3.py

This was a result of the performance changes, if a tuple is empty and we attempt to access it we will get an index out of range
```
>>> t = tuple()
>>> t[0]
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
IndexError: tuple index out of range
```
Our `test_grpc_3` wasnt checking the trailing metadata for anything so i removed them in that test. (present trailing metadata is covered in `test_grpc_1`)

GRPC resp metadata colleciton fails if tuple is empty

---

src/hypertrace/agent/instrumentation/django/__init__.py
tests/django/test_django_1.py

Since middleware chain is halted during a blocked request we weren't reporting the resp status code.

Django - set http.status_code on filter 

---

src/hypertrace/agent/config/__init__.py
src/hypertrace/agent/config/environment.py
src/hypertrace/agent/init/__init__.py

Minor log cleanup:
- we had one env log that was set to info, the rest were debug
- the exporter initialization always logged zipkin
- log the config state after env + file + defaults are done being processed at info level

Log cleanup

---

src/hypertrace/agent/filter/__init__.py
src/hypertrace/agent/filter/registry.py
src/hypertrace/agent/filter/test_registry.py
tests/django/test_django_1.py
tests/flask/test_flask_10.py
tests/grpc/test_grpc_3.py

Body evaluation may need to take some headers into account(for instance, if inspecting an ip address) - this updates the Filter.evaluate_body to also receive the header dict

Update Filter.evaluate_body to also use headers

---

README.md
src/hypertrace/agent/__init__.py
src/hypertrace/agent/autoinstrumentation/sitecustomize.py
src/hypertrace/agent/instrumentation/django/django_auto_instrumentation_compat.py
tests/django/test_django_1.py

Running django under gunicorn breaks auto instrumentation because django settings have not been configured. 
Since django relies on `django.core.wsgi`/`django.core.asgi` .`get_asgi/wsgi_application` we can wrap those functions and register django instrumentation immediately following the app being configured.

Improve django+gunicorn auto instr

---

src/hypertrace/agent/instrumentation/aws_lambda/__init__.py
src/hypertrace/agent/instrumentation/flask/__init__.py
tests/lambda/test_lambda.py

- fix If a lambda is not configured to return a response dict, dont call dict methods on it(just skip response processing)
- fix - http.url attribute was previously just reporting the path, concatenate the host + path lambda fields.

Lambda - Fix no response dict, correct reported http.url attribute

---

src/hypertrace/agent/instrumentation/aws_lambda/__init__.py

Attempting to split the undefined lambda handler name will cause an exception. In non-lambda environments we don't expect a handler function to be defined so just early return.

fix: handle case where we cant detect a lambda handler

---

setup.py

The pip check in `python_requires` only works if on newer versions of pip.  If a user is on an old version of python, it wouldn't be surprising if they are also on an older version of pip.  In this case, print an error message and exit during install.
ex:  
```
❯ python setup.py develop
sys.version_info(major=2, minor=7, micro=16, releaselevel='final', serial=0)
Hypertrace is not supported on python versions before 3.6
```

Check if on versions of python before 3.6

---

src/hypertrace/agent/config/__init__.py

We can ignore this rule, if the class is not available tests will fail when trying to load the config

protobuf 3.20 BoolValue not found but exists - add lint ignore

---

dev-requirements.txt
requirements.txt
setup.py
src/hypertrace/agent/__init__.py
src/hypertrace/agent/instrumentation/__init__.py
src/hypertrace/agent/instrumentation/fast_api/__init__.py
src/hypertrace/agent/instrumentation/fast_api/fast_api_auto_instrumentation_compat.py
src/hypertrace/agent/instrumentation/instrumentation_definitions.py
tests/conftest.py
tests/hypertrace/agent/instrumentation/fastapi/test_fastapi.py

Add fast api support
Tests check that basic span data + req data + resp data is captured.  
Tests make sure that requests can be filtered  based on headers or bodies.

Fast API Support

---

src/hypertrace/agent/instrumentation/fast_api/__init__.py
tests/hypertrace/agent/instrumentation/fastapi/test_fastapi.py

In fastapi the body can only be read once per request - using `await request.body()` causes us to consume the messages which then leads to the app hanging when the route handler tries to read the payload.
Instead, consume the body messages but cache them to return to the user handler in our wrapped_receive hook.

FastAPI Fix cache received messages

---

README.md
dev-requirements.txt
proto.sh
src/hypertrace/agent/config/config_pb2.py

Protobuf version was previously based on user installed version of proto(as mentioned here): 
https://github.com/hypertrace/pythonagent/issues/165
This creates issues when trying to bump proto versions, as generating protobuf on a newer version limits our supported minimum, even though in requirements.txt and setup.py we specify a ceiling.
For some reason httpx needs added to dev dependencies(since Friday it seems like something has changed) and 3.7+ tests continue to hang indefinitely

Add script to generate proto on known version of protoc

---

src/hypertrace/agent/__init__.py
src/hypertrace/agent/init/__init__.py
tests/hypertrace/__init__test.py
tests/integration/autoinstrumentation/requirements.txt
tests/integration/autoinstrumentation/tox.ini
tests/integration/gunicorn/flask_app/requirements.txt
tests/integration/gunicorn/requirements.txt
tests/integration/gunicorn/tox.ini

Attempting to re-init tracers after code based configuration changes would cause the existing tracer provider to error.  
This defers tracer initialization until the user calls instrument, allowing them to configure the agent through code.

Defer tracer init until ready to instrument
